export const teskroInfo = [
  "Teskro is a website that helps you generate AI-powered tests.",
  "Teskro inititally offers AWS, AZURE, GCP, COMPTIA AND LINUX FOUNDATION tests at the home page but you can make custom tests at the custom tab.",
  "You can create and customize your own quizzes.",
  "You can track your progress and performance through detailed analytics.",
  "Teskro supports various question types like multiple choice, true/false, and select two.",
  "The owner and developer of Teskro is David Naymon and his email is naymondavid@gmail.com.",
  "Teskro is open source under the MIT license, and you can find the code on GitHub at https://github.com/DavidN22/AI-TestMaker",
  "Teskro uses a custom algorithm to prevent duplicate questions in same titled tests.",
  "Tesko also uses a custom algorithm to track weak points and build tests around what the user struggles with the most.",
  "Teskro is mobile-friendly but works best on desktop browsers.",
  "Tokens are used to generate tests and refresh on their own every 2 days",
  "The stats page shows Average score, Average score by difficulty, Tests taken by provider, a Line chart of score trends over time, and a github style activity history.",
  "The history page shows every exam taken, with the date, score, provider, difficulty, weak points, and title.",
  "Creating a custom tests, requires users to navigate to Custom tab, click Create New Test, and fill in the required fields like Test Name, Description, Headline (optional), and selecting a difficulty (this can be changed later).",
  "You may delete you account and or data at any time by going to the Settings page and clicking Delete All Data or Delete History.",
  "Teskro offers other AI models that can be changed in the settings page.",
  "All created custom tests can be edited and deleted by the user.",
  "Difficulty levels for each tests are set in place but can be changed in the test configuration settings.",
  "Before making a custom tests, you can generate preview instead of create test to see what the test will look like (This will consume a token).",
  "Our newest and lastest features allow users to create custom tests via chatbot interface without leaving the chat window.",
  "This chatbot (You are the chatbot) can also answer any questions about the users test data and performance, as well as general questions about Teskro.",
];
